# Generated by Django 3.2.25 on 2024-12-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='foodapp.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='foodapp.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
