
services:

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/FoodNStuff
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=FoodNStuff.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=adminpassword  # Set your desired password here
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      - db
  

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipe_db
      - POSTGRES_USER=cschaaf
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"


